encoding: utf-8
timezone: Europe/Berlin

baseurl: http://documentation.mamp.info

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: appsolute GmbH
